version: 2

# See https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file
updates:
  - package-ecosystem: "npm"
    directory: "/"
    commit-message:
      prefix: chore
      include: scope
    labels:
      - "dependencies"
    schedule:
      interval: "weekly"
    groups:
      npm-dependencies-root:
        patterns:
          - "*"

  - package-ecosystem: "github-actions"
    directory: "/"
    commit-message:
      prefix: chore
      include: scope
    labels:
      - "github_actions"
    groups:
      actions:
        patterns:
          - "*"
    schedule:
      interval: "weekly"